// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEjpG5wCL9FS7E_nLULRxduic7IxZvcUY',
    appId: '1:126254240508:web:183b29160470984ffdfd79',
    messagingSenderId: '126254240508',
    projectId: 'my-expense-tkr',
    authDomain: 'my-expense-tkr.firebaseapp.com',
    storageBucket: 'my-expense-tkr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8kVK5-pTPyLqyTCaUycMlVxMlxlvUn5o',
    appId: '1:126254240508:android:47764c078b95d7b7fdfd79',
    messagingSenderId: '126254240508',
    projectId: 'my-expense-tkr',
    storageBucket: 'my-expense-tkr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHHU-S5_wXqqAB_z_B6M7rmjV4XVIxMJE',
    appId: '1:126254240508:ios:5fcb77810b32f98efdfd79',
    messagingSenderId: '126254240508',
    projectId: 'my-expense-tkr',
    storageBucket: 'my-expense-tkr.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHHU-S5_wXqqAB_z_B6M7rmjV4XVIxMJE',
    appId: '1:126254240508:ios:5fcb77810b32f98efdfd79',
    messagingSenderId: '126254240508',
    projectId: 'my-expense-tkr',
    storageBucket: 'my-expense-tkr.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEjpG5wCL9FS7E_nLULRxduic7IxZvcUY',
    appId: '1:126254240508:web:3633e404698c4564fdfd79',
    messagingSenderId: '126254240508',
    projectId: 'my-expense-tkr',
    authDomain: 'my-expense-tkr.firebaseapp.com',
    storageBucket: 'my-expense-tkr.firebasestorage.app',
  );
}
